#!/usr/bin/env python3
"""
Command-line script to run the Bricks Deal Crawl package.
"""

import sys
import os

# Add the parent directory to the path so we can import the package
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from bricks_deal_crawl.main import main

if __name__ == "__main__":
    sys.exit(main())